### ISSUE TITLE
TypeError: querystring_1.default.encode is not a function when searching for movie

### ISSUE THREAD

**Issue by Hoidi** [blakejoy/tmdb-ts#13]
**Describe the bug**
When I call the following function

`const movies = await tmdb.search.movies({ query: 'Babylon' });`

I get this error
`TypeError: querystring_1.default.encode is not a function` in `search.ts:49`

However, it seems the code is working in my console as I can log stuff related to the search results. See Additional information why that might be the case

**To Reproduce**
1. Call `tmdb.search.movies` with some `query` parameter

**Expected behavior**
A search result should be returned

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [firefox]
 - Version [110]
 
 **Additional information**
I also get the following warning
```
Module "querystring" has been externalized for browser compatibility. Cannot access "querystring.encode" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

**Comment by blakejoy** [comment]
Ahh I see. Initially my thought process when creating this wrapper was to only use it server side. It seems like in your case you're using on the client ?

**Comment by Hoidi** [comment]
That is the case indeed
