### ISSUE TITLE
Some properties/endpoints are not available on TMDB type

### ISSUE THREAD

**Issue by Hoidi** [blakejoy/tmdb-ts#17]
**Describe the bug**
Some properties/endpoints are not available from the latest npm version (0.1.5) 

The ones that are not included are:
* review
* discover
* people
* find
* keywords
* collections

Example error
`Property 'people' does not exist on type 'TMDB'`

**Expected behavior**
The properties should be available on the type TMDB

**Additional context**
I'm pretty sure there is something wrong with the relase process. You can look at the code for the package [here](https://www.npmjs.com/package/tmdb-ts?activeTab=code) and there it looks like it includes old code.

**Comment by blakejoy** [comment]
Should be fixed now. I still need to work on getting this automated, it was a mishap on my part 😅

**Comment by Hoidi** [comment]
Thanks for being so fast! No worries. However, it looks like the .README dissapeared somewhere on the way to npm. Not that it matters too much right now but you might want to check it out before next release :)

**Comment by blakejoy** [comment]
> Thanks for being so fast! No worries. However, it looks like the .README dissapeared somewhere on the way to npm. Not that it matters too much right now but you might want to check it out before next release :)
> 
> EDIT: Nevermind, looks like it has appeared now

🪄🪄🪄
