### ISSUE TITLE
Is passing language query param possible?

### ISSUE THREAD

**Issue by reaver585** [blakejoy/tmdb-ts#39]
Hi. Thanks for writing this useful tool.

My question is the following:
I would like to query the [movie details](https://developer.themoviedb.org/reference/movie-details), using a language that is not English.

Is this possible?

Thanks in advance.

**Comment by jeremyVignelles** [comment]
I have the same issue when trying to call this code:

```ts
        const resultats = await tmdb.search.movies({
            language: 'fr-FR',
            query: recherche,
            page: page,
        })
```

The binding does not have this parameter, but it's just a typescript error (the code does work), so you can ignore it with typescript techniques like `as any`

```ts
        const resultats = await tmdb.search.movies({
            language: 'fr-FR',
            query: recherche,
            page: page,
        } as any)
```

This should be fixed in the library, and I'm going to send a PR for that soon.

**Comment by jeremyVignelles** [comment]
PR #42 submitted :)
