### ISSUE TITLE
Feature Request: Company data

### ISSUE THREAD

**Issue by benlei** [blakejoy/tmdb-ts#40]
**Is your feature request related to a problem? Please describe.**

Right now it seems like this library is missing the ability to fetch company details/alternative names/images. Can this be added in?

This would be for the following endpoints:

- https://developer.themoviedb.org/reference/company-details
- https://developer.themoviedb.org/reference/company-alternative-names
- https://developer.themoviedb.org/reference/company-images

**Comment by blakejoy** [comment]
Closed #41
