### ISSUE TITLE
Release 1.5.0 on npm

### ISSUE THREAD

**Issue by marph91** [blakejoy/tmdb-ts#43]
Hi,

I would like to use the aggregated credits (https://github.com/blakejoy/tmdb-ts/commit/ab1925d32c15beb9c181135f2e825338fb4bcf46) with version 1.5.0. This version seems to be not yet on npm. Probably because the publish workflow didn't trigger. Is there an estimate when it will be released?

**Comment by blakejoy** [comment]
Should be released now!

**Comment by marph91** [comment]
Thanks, it works :)
