### ISSUE TITLE
Types do not include errors

### ISSUE THREAD

**Issue by lucassardois** [blakejoy/tmdb-ts#47]
**Describe the bug**
API endpoint are typed without reflecting potential errors. This is an issue since HTTPs errors (400+) do not reject promise but instead resolve them with an object not matching the type.

**To Reproduce**
Executing the following code will return an object not matching the type because TMDB send a 401 request with a descriptive error.
```js
new TMDB('wrongApiToken').account.details()
```

**Expected behavior**
The previous code should either reject in case of error (ex: when the API token is unauthorized), or include the type error in the resolved type.

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Browser: Firefox
 - Version: 121.0

**Comment by blakejoy** [comment]
Just pushed an implementation for handling api errors. Let me know if that works. @lucassardois

**Comment by blakejoy** [comment]
Hmmm I guess would you rather the whole response object or just the response?
