### ISSUE TITLE
Enum type not defined at runtime

### ISSUE THREAD

**Issue by pypp** [blakejoy/tmdb-ts#53]
**Describe the bug**

**To Reproduce**
When trying to use one of the enums in a react typescript application I’m getting the following error: 
`cannot read property of undefined`. 
I think this issue is caused because of the `declare` keyword when defining the enums.

**Expected behavior**
To be able to use the enums in runtime

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 64-bit
 - Browser Chrome
 - Version 121

**Smartphone (please complete the following information):**

**Comment by blakejoy** [comment]
I believe it's related to how const enums are compiled. I will change these to just enums. In a major version bump, I'll convert to immutable objects... separating the types out a bit.
