### ISSUE TITLE
Forcing Style rules

### ISSUE THREAD

**Issue by Der-Penz** [blakejoy/tmdb-ts#8]
### consistent styling throughout the whole project would be helpful

I personally had a problem adding features to this repo because my dev environment was set up with a different styling (Indentation 4-Tabs instead of 2-Spaces) and auto-format on save, which changed source code written from someone else completely.

## Solution
- adding prettier with a config style so everybody can easily style his code in a consistent matter
- adding github actions to automatically run ```npm format``` on a pull request so only correctly formatted code can be merged
- adding .husky to automatically run ```npm format``` before committing your changes to never commit incorrectly formatted code while not being forced to remember to do it every time

**Comment by blakejoy** [comment]
I may work on adding github actions so that formatting, pushing to npm registry and etc is automated.

**Comment by Der-Penz** [comment]
Sounds good

**Comment by blakejoy** [comment]
Closed in #22
